# Generated by Django 5.2.3 on 2025-11-20 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_appointments', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_reminders', models.BooleanField(default=True)),
                ('push_appointments', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC-5', max_length=50)),
                ('date_format', models.CharField(default='MM/DD/YYYY', max_length=20)),
                ('time_format', models.CharField(default='12h', max_length=10)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('patients', 'Patients Only'), ('private', 'Private')], default='patients', max_length=20)),
                ('show_online_status', models.BooleanField(default=True)),
                ('read_receipts', models.BooleanField(default=True)),
                ('data_sharing', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('session_timeout', models.CharField(default='30', max_length=10)),
                ('password_last_changed', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
