# Generated by Django 5.2.3 on 2025-11-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='data_sharing',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='email_appointments',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='email_messages',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='email_reminders',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='password_last_changed',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='profile_visibility',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='push_appointments',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='push_messages',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='read_receipts',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='session_timeout',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_online_status',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='two_factor_enabled',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='date_format',
            field=models.CharField(choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='MM/DD/YYYY', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='time_format',
            field=models.CharField(choices=[('12h', '12 Hour'), ('24h', '24 Hour')], default='12h', max_length=5),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(choices=[('UTC-5', 'EST (UTC-5)'), ('UTC-6', 'CST (UTC-6)'), ('UTC-7', 'MST (UTC-7)'), ('UTC-8', 'PST (UTC-8)')], default='UTC-5', max_length=10),
        ),
    ]
