# Generated by Django 5.2.3 on 2025-11-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0003_alter_usersettings_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='is_profile_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_online_status',
            field=models.BooleanField(default=True),
        ),
    ]
