# Generated by Django 5.2.3 on 2025-11-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0004_usersettings_is_profile_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='is_profile_public',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('patients_only', 'Patients Only')], default='public', max_length=20),
        ),
    ]
