# Generated by Django 5.2.7 on 2025-11-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0005_remove_usersettings_is_profile_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
