# Generated by Django 5.2.7 on 2025-11-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0006_usersettings_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
