# Generated by Django 5.2.7 on 2025-11-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0007_usersettings_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
