# Generated by Django 5.2.7 on 2025-11-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0008_usersettings_card_brand_usersettings_card_last4'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='card_exp_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='card_exp_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
