# Generated by Django 5.2.7 on 2025-11-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0009_usersettings_card_exp_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='session_duration',
            field=models.IntegerField(choices=[(15, '15 Minutes'), (30, '30 Minutes'), (60, '1 Hour'), (120, '2 Hours')], default=60),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sn', 'Sinhala'), ('tm', 'Tamil')], default='en', max_length=5),
        ),
    ]
