# Generated by Django 5.2.7 on 2025-11-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0010_usersettings_session_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='email_appointment_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_appointment_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='email_new_messages',
            field=models.BooleanField(default=True),
        ),
    ]
