# Generated by Django X.X.X on 2025-11-21 12:50 (Your auto-generated header)

from django.db import migrations, models
from datetime import datetime # CRITICAL IMPORT for the data migration

# --- 1. Custom Data Migration Function ---
def combine_date_time(apps, schema_editor):
    """
    Combines the existing 'date' and 'time' fields into the new 'start_time' field
    for all existing Appointment records.
    """
    # Get the historical version of the Appointment model for this migration
    Appointment = apps.get_model('appointments', 'Appointment')

    for appointment in Appointment.objects.all():
        if appointment.date and appointment.time:
            # Combine the date and time objects to create the full datetime object
            # Note: The time object from the database might need to be casted implicitly
            try:
                appointment.start_time = datetime.combine(appointment.date, appointment.time)
                # Use update_fields to save only the field being modified
                appointment.save(update_fields=['start_time'])
            except Exception as e:
                # Basic error handling in case of bad data
                print(f"Error combining date/time for appointment ID {appointment.id}: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        # 1. Add the new field to the database schema
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),

        # 2. Run the custom function to populate existing data
        migrations.RunPython(combine_date_time, reverse_code=migrations.RunPython.noop),
    ]
