# Generated by Django 5.2.3 on 2025-11-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_progressnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
