# Generated by Django 5.2.3 on 2025-07-31 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_counselorprofile_full_name_doctorprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorprofile',
            name='license_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
