# Generated by Django 5.2.3 on 2025-08-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_counselorprofile_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
        ),
    ]
