# Generated by Django 5.2.3 on 2025-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_counselorprofile_rating_doctorprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A professional bio or statement for patients to see.', null=True),
        ),
        migrations.AddField(
            model_name='counselorprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A professional bio or statement for patients to see.', null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
