# Generated by Django 5.2.7 on 2025-10-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_providerschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/counselors/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/doctors/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/patients/'),
        ),
    ]
