# Generated by Django 5.2.3 on 2025-11-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_counselorprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorprofile',
            name='nic',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='nic',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='nic',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
