# Generated by Django 5.2.3 on 2025-11-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_counselorprofile_nic_alter_doctorprofile_nic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', max_length=10),
        ),
    ]
