# Generated by Django 5.2.3 on 2025-11-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_counselorprofile_nic_alter_doctorprofile_nic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('patients_only', 'Patients Only'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('patients_only', 'Patients Only'), ('private', 'Private')], default='public', max_length=20),
        ),
    ]
