# Generated by Django 5.2.7 on 2025-11-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_counselorprofile_profile_visibility_and_more'),
        ('authapp', '0010_patientprofile_risk_level'),
    ]

    operations = [
    ]
