# Generated by Django 5.2.3 on 2025-11-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_patientprofile_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorprofile',
            name='license_document',
            field=models.FileField(blank=True, help_text='Upload your counselor license for verification.', null=True, upload_to='licenses/counselors/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_document',
            field=models.FileField(blank=True, help_text='Upload your medical license for verification.', null=True, upload_to='licenses/doctors/'),
        ),
    ]
