# Generated by Django 5.2.7 on 2025-11-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_merge_20251123_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselorprofile',
            name='profile_visibility',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='profile_visibility',
        ),
    ]
