# Generated by Django 5.2.7 on 2025-11-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_counselorprofile_license_document_and_more'),
        ('authapp', '0012_remove_counselorprofile_profile_visibility_and_more'),
    ]

    operations = [
    ]
