# Generated by Django 5.2.7 on 2025-11-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_merge_20251124_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='chronic_illness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('E', 'Employed'), ('U', 'Unemployed/Seeking'), ('S', 'Student'), ('R', 'Retired'), ('H', 'Homemaker')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='financial_stress_level',
            field=models.IntegerField(blank=True, help_text='Self-reported financial stress scale (1=Low, 5=High)', null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_assessment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='latest_phq9_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single/Never Married'), ('M', 'Married/Cohabiting'), ('D', 'Divorced/Separated'), ('W', 'Widowed')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='mh_diagnosis_history',
            field=models.BooleanField(default=False, help_text='History of prior mental health diagnosis.'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='substance_use',
            field=models.BooleanField(default=False, help_text='History of significant substance/alcohol use.'),
        ),
    ]
