# Generated by Django 5.2.7 on 2025-11-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_merge_20251124_0006'),
        ('authapp', '0013_merge_20251124_0023'),
    ]

    operations = [
    ]
