# Generated by Django 5.2.7 on 2025-11-25 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_merge_20251125_1714'),
        ('authapp', '0014_patientprofile_chronic_illness_and_more'),
    ]

    operations = [
    ]
