# Generated by Django 5.2.7 on 2025-10-25 13:11

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='moodentry',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Mood Entries'},
        ),
        migrations.RenameField(
            model_name='moodentry',
            old_name='patient',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='moodentry',
            unique_together={('user', 'date')},
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 25, 13, 11, 53, 131494, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='anxiety',
            field=models.IntegerField(help_text='Anxiety level from 1-10'),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='energy',
            field=models.IntegerField(help_text='Energy level from 1-10'),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.IntegerField(help_text='Mood level from 1-10'),
        ),
    ]
