# Generated by Django 5.2.7 on 2025-11-15 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('category', models.CharField(choices=[('Mental Health', 'Mental Health'), ('Physical Health', 'Physical Health'), ('Nutrition', 'Nutrition'), ('Sleep', 'Sleep'), ('Social', 'Social'), ('Productivity', 'Productivity')], default='Mental Health', max_length=50)),
                ('target', models.IntegerField(default=1, help_text='Target occurrences per frequency period.')),
                ('current', models.IntegerField(default=0, help_text='Current count for the current period (e.g., this day/week).')),
                ('streak', models.IntegerField(default=0, help_text='Current consecutive streak.')),
                ('color', models.CharField(default='hsl(210, 80%, 50%)', help_text='HSL color string for frontend display.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_completed', models.DateField(blank=True, null=True)),
                ('completed_today', models.BooleanField(default=False)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
