# Generated by Django 5.2.7 on 2025-11-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='color',
            field=models.CharField(default='hsl(210, 80%, 50%)', help_text='HSL color string for frontend display.', max_length=50),
        ),
    ]
