# Generated by Django 5.2.7 on 2025-11-20 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='completed_today',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='current',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='last_completed',
        ),
        migrations.AddField(
            model_name='habit',
            name='last_completed_period_end',
            field=models.DateField(blank=True, help_text='End date of the last period where the entire habit was completed.', null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='streak',
            field=models.IntegerField(default=0, help_text='Current consecutive streak of full habit completion.'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='target',
            field=models.IntegerField(default=1, help_text='Number of target *tasks* required for full habit completion in a period.'),
        ),
        migrations.CreateModel(
            name='HabitTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='habits.habit')),
            ],
            options={
                'verbose_name': 'Habit Task',
                'verbose_name_plural': 'Habit Tasks',
                'ordering': ['created_at'],
                'unique_together': {('habit', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HabitTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='habits.habittask')),
            ],
            options={
                'verbose_name': 'Habit Task Completion',
                'verbose_name_plural': 'Habit Task Completions',
                'indexes': [models.Index(fields=['task', 'completed_at'], name='habits_habi_task_id_6750ed_idx')],
            },
        ),
    ]
