# Generated by Django 5.2.3 on 2025-11-16 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('image', 'Image')], max_length=20)),
                ('file', models.FileField(upload_to='content_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to=models.Q(('role', 'doctor'), ('role', 'counselor'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, limit_choices_to={'role': 'user'}, related_name='shared_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
