# blogs/urls.py

# from django.urls import path, include
# from rest_framework.routers import DefaultRouter
# from .views import BlogPostViewSet

# # Create a router instance
# router = DefaultRouter()

# # Register the ViewSet. This automatically creates all the necessary URLs:
# # /api/blogs/ (for listing and creating)
# # /api/blogs/{id}/ (for retrieving, updating, deleting)
# # /api/blogs/{id}/rate/ (for our custom rating action)
# router.register(r'', BlogPostViewSet, basename='blogpost')


# # The urlpatterns includes all the routes generated by the router
# urlpatterns = [
#     path('', include(router.urls)),
# ]











# blog/urls.py

from rest_framework.routers import DefaultRouter
from .views import BlogPostViewSet

# Create a router instance
router = DefaultRouter()

# Register the ViewSet with a base name 'blogs'
# This creates routes like:
# /api/blogs/ (GET for list, POST for create)
# /api/blogs/{id}/ (GET/PUT/PATCH/DELETE for detail)
router.register(r'blogs', BlogPostViewSet, basename='blogs')

# The urlpatterns includes all the routes generated by the router
urlpatterns = router.urls
