# blog/urls.py

from rest_framework.routers import DefaultRouter
from .views import BlogPostViewSet

# Create a router instance
router = DefaultRouter()

# Register the ViewSet with a base name 'blogs'
# This creates routes like:
# /api/blogs/ (GET for list, POST for create)
# /api/blogs/{id}/ (GET/PUT/PATCH/DELETE for detail)
router.register(r'blogs', BlogPostViewSet, basename='blogs')

# The urlpatterns includes all the routes generated by the router
urlpatterns = router.urls
