# Generated by Django 5.2.7 on 2025-11-19 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_sequence_length', models.IntegerField(help_text='The highest level/length of the sequence successfully matched.')),
                ('total_attempts', models.IntegerField(help_text='The number of attempts made before failing.')),
                ('post_game_mood', models.IntegerField(choices=[(1, 'Very Stressed'), (2, 'Stressed'), (3, 'Neutral'), (4, 'Calm'), (5, 'Very Calm')], default=3, help_text="User's reported mood after completing the game (1-5 scale).")),
                ('perceived_effort', models.IntegerField(blank=True, help_text='How much effort did you feel you exerted? (1=None, 10=Max)', null=True)),
                ('stress_reduction_rating', models.IntegerField(blank=True, help_text='Do you feel calmer after the game? (1=No, 10=Definitely Yes)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the result was recorded.')),
                ('user', models.ForeignKey(help_text='The user who performed the test.', on_delete=django.db.models.deletion.CASCADE, related_name='memory_game_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memory Game Result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReactionTimeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_time_ms', models.IntegerField(help_text='The calculated reaction time in milliseconds.')),
                ('post_game_mood', models.IntegerField(choices=[(1, 'Very Stressed'), (2, 'Stressed'), (3, 'Neutral'), (4, 'Calm'), (5, 'Very Calm')], default=3, help_text="User's reported mood after completing the game (1-5 scale).")),
                ('perceived_effort', models.IntegerField(blank=True, help_text='How much effort did you feel you exerted? (1=None, 10=Max)', null=True)),
                ('stress_reduction_rating', models.IntegerField(blank=True, help_text='Do you feel calmer after the game? (1=No, 10=Definitely Yes)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the result was recorded.')),
                ('user', models.ForeignKey(help_text='The user who performed the test.', on_delete=django.db.models.deletion.CASCADE, related_name='reaction_time_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StroopGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_correct', models.IntegerField(help_text='The total number of correct answers (out of N trials).')),
                ('interference_score_ms', models.IntegerField(help_text='The difference in average time between incongruent and congruent trials (ms).')),
                ('total_time_s', models.FloatField(help_text='The total time taken to complete all trials (seconds).')),
                ('post_game_mood', models.IntegerField(choices=[(1, 'Very Stressed'), (2, 'Stressed'), (3, 'Neutral'), (4, 'Calm'), (5, 'Very Calm')], default=3, help_text="User's reported mood after completing the game (1-5 scale).")),
                ('perceived_effort', models.IntegerField(blank=True, help_text='How much effort did you feel you exerted? (1=None, 10=Max)', null=True)),
                ('stress_reduction_rating', models.IntegerField(blank=True, help_text='Do you feel calmer after the game? (1=No, 10=Definitely Yes)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the result was recorded.')),
                ('user', models.ForeignKey(help_text='The user who performed the test.', on_delete=django.db.models.deletion.CASCADE, related_name='stroop_game_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stroop Game Result',
                'ordering': ['-created_at'],
            },
        ),
    ]
