# Generated by Django 5.2.7 on 2025-11-20 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalGames', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LongestNumberGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_number_length', models.IntegerField(help_text='The highest length of the number successfully recalled.')),
                ('total_attempts', models.IntegerField(help_text='The total number of trials/attempts made.')),
                ('post_game_mood', models.IntegerField(choices=[(1, 'Very Stressed'), (2, 'Stressed'), (3, 'Neutral'), (4, 'Calm'), (5, 'Very Calm')], default=3, help_text="User's reported mood after completing the game (1-5 scale).")),
                ('perceived_effort', models.IntegerField(blank=True, help_text='How much effort did you feel you exerted? (1=None, 10=Max)', null=True)),
                ('stress_reduction_rating', models.IntegerField(blank=True, help_text='Do you feel calmer after the game? (1=No, 10=Definitely Yes)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the result was recorded.')),
                ('user', models.ForeignKey(help_text='The user who performed the test.', on_delete=django.db.models.deletion.CASCADE, related_name='longest_number_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Longest Number Game Result',
                'ordering': ['-created_at'],
            },
        ),
    ]
