# Generated by Django 5.2.7 on 2025-11-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalGames', '0002_longestnumbergameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='longestnumbergameresult',
            name='total_reaction_time_ms',
            field=models.IntegerField(default=0, help_text='The total time in milliseconds spent inputting the correct answers across all successful levels.'),
        ),
    ]
