# Generated by Django 5.2.7 on 2025-11-20 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalGames', '0003_longestnumbergameresult_total_reaction_time_ms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumpuzGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken_s', models.FloatField(help_text='The time taken to solve the puzzle (in seconds).')),
                ('puzzle_size', models.CharField(help_text="The size of the puzzle solved (e.g., '3x3', '4x4').", max_length=10)),
                ('moves_made', models.IntegerField(help_text='The total number of moves made to solve the puzzle.')),
                ('post_game_mood', models.IntegerField(choices=[(1, 'Very Stressed'), (2, 'Stressed'), (3, 'Neutral'), (4, 'Calm'), (5, 'Very Calm')], default=3, help_text="User's reported mood after completing the game (1-5 scale).")),
                ('perceived_effort', models.IntegerField(blank=True, help_text='How much effort did you feel you exerted? (1=None, 10=Max)', null=True)),
                ('stress_reduction_rating', models.IntegerField(blank=True, help_text='Do you feel calmer after the game? (1=No, 10=Definitely Yes)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the result was recorded.')),
                ('user', models.ForeignKey(help_text='The user who performed the test.', on_delete=django.db.models.deletion.CASCADE, related_name='numpuz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Numpuz Game Result',
                'ordering': ['-created_at'],
            },
        ),
    ]
