# Generated by Django 5.2.7 on 2025-10-25 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_counselorprofile_profile_picture_and_more'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='shared_with_counselor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_journal_entries', to='authapp.counselorprofile'),
        ),
    ]
