# Generated by Django 5.2.7 on 2025-11-22 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcomment_blograting_blogreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blograting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogreaction',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='blograting',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='blogreaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blograting',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='blogreaction',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blograting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogreaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='blogreaction',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='blogreaction',
            name='type',
        ),
    ]
