# Generated by Django 5.2.7 on 2025-11-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blograting_options_alter_blogreaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('insightful', 'Insightful')], default='like', max_length=20),
        ),
    ]
