# Generated by Django 5.2.7 on 2025-11-24 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogreaction_reaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['createdAt']},
        ),
        migrations.AlterField(
            model_name='blograting',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='blogreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('heart', 'Heart'), ('insightful', 'Insightful')], default='like', max_length=20),
        ),
    ]
